### ISSUE TITLE
Problem mit ständig ändernden Links beheben

### ISSUE THREAD

**Issue by olzimmerberg** [olzimmerberg/olz-website#193]
z.B. `/files/aktuell/123/001.pdf` => `files/2020-ausschreibung-milchsuppencup.pdf`

### Mühsames Beispiel:

- `DATEI1` in einem Aktuell-Eintrag muss aktualisiert werden
- Im selben Eintrag gibt es auch eine `DATEI2`

Man kann jetzt entweder
- `DATEI1` löschen
- Neue Datei als `DATEI2` hochladen
=> Dateien sind jetzt vertauscht!

oder:
- `DATEI1` und `DATEI2` löschen
- Die neue `DATEI1` hochladen
- Ein Backup von `DATEI2` hochladen
=> benötigt ein backup von `DATEI2`

**Comment by allestuetsmerweh** [comment]
Das wird mit den neuen Aktuell-Einträgen gelöst! Neu ist es nicht mehr `DATEI<index>`, sondern `DATEI<hash>`
