### ISSUE TITLE
Icons in `src/icns/` durch SVGs ersetzen

### ISSUE THREAD

**Issue by olzimmerberg** [olzimmerberg/olz-website#92]
...und evtl. auch das Aussehen überarbeiten.

gut wäre auch ein PNG-Fallback (CI könnte die PNGs generieren, am besten in einfacher und `@2x` Hi-DPI Auflösung).

**Comment by idefix-lutece** [comment]
Benötigen wir den Fallback für die alten Browser wirklich?

Auf dem Desktop ist die Unterstützung bei ca. 99.99% der Zugriffe. Im Mobile Bereich sind es ca 99.25%

Für die 0.75% Browserzugriffe im Mobile Bereich ist die Unterstützung des SVG Features ungeklärt. Z.b der Samsung Internet basiert auf dem Chronium der das Feature unterstützt.

Wenn einer dieser Besucher die Picktogramme nicht angeziegt bekommt weil er keine aktuellen oder gängigen Browser verwenden will, dann ist das ein Stückweit sein Problem.


Details:

Gemäss https://caniuse.com/#feat=mdn-svg_elements_svg können fast alle Browser SVG darstellen.

Die Browser Statistik in der Schweiz zeigt folgende Anteile mit inkompatiblen Browser:
https://gs.statcounter.com/browser-version-market-share/all/switzerland/#monthly-201904-202004

Samsung Internet 1.0 0.01%
Samsung Internet 1.1 0.02%
Samsung Internet 2.0 0.03%
Samsung Internet 2.1 0.03%
Samsung Internet 3.3 0.01%
Samsung Internet 4.0 0.01%
Samsung Internet 5.2 0.01%
Samsung Internet 7.0 0.01%
Samsung Internet 7.2 0.01%
Samsung Internet 7.4 0.02%
Samsung Internet 8.2 0.02%
Samsung Internet 9.0 0.02%
Samsung Internet 9.2 0.06%
Samsung Internet 9.4 0.05%
Samsung Internet 10.1 0.13%
Samsung Internet 10.2 0.24%
QQ Browser 8.1 0.01%
QQ Browser 10.5 0.06%
IE 10 0.01%

**Comment by olzimmerberg** [comment]
Stimmt. Unsere Stats zeigen ebenfalls, dass *falls* jemand Internet Explorer benützt, dies Version 9 oder 11 ist (beide unterstützen SVGs).
Wir können einfach die SVGs einbinden.
